# Generated by Django 4.0.6 on 2022-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_alter_items_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemName',
            field=models.CharField(max_length=50),
        ),
    ]
