# Generated by Django 4.0.6 on 2022-11-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_alter_items_itemname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
