# Generated by Django 4.0.6 on 2022-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='itemCode',
            field=models.CharField(max_length=100),
        ),
    ]
