# Generated by Django 4.0.4 on 2022-11-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0005_alter_orders_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemName',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
