# Generated by Django 4.0.6 on 2022-11-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0006_orders_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemPrice',
            field=models.FloatField(default=0),
        ),
    ]
