# Generated by Django 4.0.6 on 2022-11-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0007_orders_itemprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itemPrice',
            new_name='totalPrice',
        ),
    ]
