# Generated by Django 4.0.6 on 2022-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0009_orders_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='itemPrice',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
